version: '3.8'

services:
  mongo:
    image: mongo
    container_name: books-data
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: books
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
